### PR TITLE
Fix to integrate preview email with Swoosh

### PR DESCRIPTION
**Pull request by joseluistorres**
https://github.com/Iowa-Elixir/reunions/issues/7

I setup the local to be able to visualize the email 'sent'
for :dev only.

I still have to check how to work with the coherence templates though.

### CODE REVIEW

**Comment by cartothemax** [comment]
@joseluistorres does this fire up a server that lets you check out the email or do you need to navigate to `/dev/mailbox` to checkout the emails?  I wanted to test it out and see how it works.  

Thanks!

**Comment by joseluistorres** [comment]
It doesn't start the server, but you can check the emails by going to `localhost:4000/dev/mailbox`

**Comment by joseluistorres** [comment]
All, I'm going to merge this one to move into something else, I'm not sure what's needed to set up the CIs @codebycliff

**Comment by codebycliff** [comment]
@joseluistorres I have branches with both CircleCI and Semaphore working. I was thinking about getting a Travis branch working too, just for comparison purposes. If we want to decide on one of the ones I have working, then we can just move forward with it. What do you think?

**Comment by joseluistorres** [comment]
Sure @codebycliff I don't have any preference really, do you?

**Pull request merged**
