### PR TITLE
Add reunion model

### PR DESCRIPTION
**Pull request by codebycliff**
This pull requests adds a basic `Reunion` model that we will expand upon as we go. Right now the `location` is just represented as a string column. This clearly will not be the end goal for this attribute. I'm not sure how meetup.com models this. It looks like they might have a table for locations which would mean this field would become a foreign key reference. There are other options too, such as storing city, state, country, etc. Let me know what you guys think.

I expanded on the tests just a little bit. Usually, I don't test validations as I believe that to be the frameworks responsibility. I went ahead and tested the validations in this pull request because I wasn't sure your guy's opinions on this.

### CODE REVIEW

**Comment by joseluistorres** [comment]
It looks good to me, my only concern is that there's no "owner" of the reunions, should we add it in another migration?
Also make sure you squash your commits.

**Comment by codebycliff** [comment]
Yeah, I figured that association can be added when we tackle creating a Reunion. There's no `User` model in master yet, so it would be hard to add until later. My vote would be to get both these in master and then go from there. Smaller the changes the better.

Also, I just planned on using Github's squash merge to take care of the squashing. It not only squashes the commits, but adds the pull request description and stuff to the commit message.

**Comment by joseluistorres** [comment]
@codebycliff could you resolve conflicts so I can merge it 🍸

**Comment by codebycliff** [comment]
Conflicts resolved. Don't forget to squash merge.

**Pull request merged**
